# Generated by Django 4.2.7 on 2025-09-01 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('customers', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Subscription for this invoice (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='customer',
            field=models.ForeignKey(help_text='Customer for this billing cycle', on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='billingcycle',
            name='subscription',
            field=models.ForeignKey(help_text='Subscription for this billing cycle', on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='subscriptions.subscription'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice'], name='billing_pay_invoice_147afb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer'], name='billing_pay_custome_5800fd_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='billing_pay_status_b7739e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='billing_pay_payment_0825d6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='billing_pay_externa_fdfe9a_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='billing_pay_transac_904624_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='billing_pay_created_a6e2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['customer'], name='billing_inv_custome_e746e8_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['subscription'], name='billing_inv_subscri_d72937_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='billing_inv_invoice_70511c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='billing_inv_due_dat_e51895_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['issue_date'], name='billing_inv_issue_d_0996ee_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['customer'], name='billing_bil_custome_ce8b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['subscription'], name='billing_bil_subscri_6cf564_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['status'], name='billing_bil_status_33ef9a_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['start_date'], name='billing_bil_start_d_077ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['end_date'], name='billing_bil_end_dat_9e9664_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billingcycle',
            unique_together={('customer', 'subscription', 'cycle_number')},
        ),
    ]
