# Generated by Django 4.2.7 on 2026-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date when invoice was sent to customer",
                null=True,
            ),
        ),
    ]
