# Generated by Django 4.2.7 on 2025-09-01 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '__first__'),
        ('customers', '0001_initial'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username for PPPoE or router access', max_length=100, unique=True)),
                ('password', models.CharField(help_text='Password for PPPoE or router access', max_length=100)),
                ('access_method', models.CharField(choices=[('pppoe', 'PPPoE'), ('static_ip', 'Static IP'), ('dhcp', 'DHCP')], default='pppoe', help_text='Access method for this subscription', max_length=20)),
                ('static_ip', models.GenericIPAddressField(blank=True, help_text='Static IP address (if applicable)', null=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address of customer device', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='pending', help_text='Subscription status', max_length=20)),
                ('start_date', models.DateField(help_text='Subscription start date')),
                ('end_date', models.DateField(blank=True, help_text='Subscription end date (optional)', null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, help_text='Monthly fee for this subscription', max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=0, help_text='One-time setup fee', max_digits=10)),
                ('data_used', models.DecimalField(decimal_places=2, default=0, help_text='Data used in GB', max_digits=15)),
                ('data_reset_date', models.DateField(blank=True, help_text='Date when data usage was last reset', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer for this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('plan', models.ForeignKey(help_text='Internet plan for this subscription', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
                ('router', models.ForeignKey(help_text='Router for this subscription', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='network.router')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='subscriptio_custome_a0857d_idx'), models.Index(fields=['plan'], name='subscriptio_plan_id_a5efcf_idx'), models.Index(fields=['router'], name='subscriptio_router__9a971e_idx'), models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'), models.Index(fields=['username'], name='subscriptio_usernam_7d6b79_idx'), models.Index(fields=['start_date'], name='subscriptio_start_d_680d80_idx'), models.Index(fields=['created_at'], name='subscriptio_created_09827c_idx')],
            },
        ),
    ]
