# Generated by Django 4.2.7 on 2025-09-01 14:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Plan description')),
                ('download_speed', models.DecimalField(decimal_places=2, help_text='Download speed', max_digits=10)),
                ('upload_speed', models.DecimalField(decimal_places=2, help_text='Upload speed', max_digits=10)),
                ('speed_unit', models.CharField(choices=[('mbps', 'Mbps'), ('gbps', 'Gbps')], default='mbps', help_text='Speed unit', max_length=10)),
                ('data_quota', models.DecimalField(blank=True, decimal_places=2, help_text='Data quota (leave empty for unlimited)', max_digits=10, null=True)),
                ('quota_unit', models.CharField(choices=[('gb', 'GB'), ('tb', 'TB'), ('unlimited', 'Unlimited')], default='gb', help_text='Quota unit', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Monthly price', max_digits=10)),
                ('setup_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='One-time setup fee', max_digits=10)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing cycle', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Is plan active')),
                ('is_featured', models.BooleanField(default=False, help_text='Is featured plan')),
                ('is_popular', models.BooleanField(default=False, help_text='Is popular plan')),
                ('features', models.JSONField(default=list, help_text='List of plan features')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['is_active'], name='plans_plan_is_acti_50e816_idx'), models.Index(fields=['price'], name='plans_plan_price_2f56f0_idx'), models.Index(fields=['is_featured'], name='plans_plan_is_feat_bf410c_idx'), models.Index(fields=['is_popular'], name='plans_plan_is_popu_e537df_idx')],
            },
        ),
    ]
