# Generated by Django 4.2.7 on 2026-02-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_router_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="snmp_community",
            field=models.CharField(help_text="SNMP community string", max_length=100),
        ),
    ]
