# Generated by Django 4.2.7 on 2026-02-25 20:21

import core.fields
from django.db import migrations

def encrypt_passwords(apps, schema_editor):
    Router = apps.get_model('network', 'Router')
    for router in Router.objects.all().iterator():
        # Saving the object triggers EncryptedCharField.get_prep_value()
        # which encrypts the password if it's plaintext
        router.save()

class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_router_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="router",
            name="password",
            field=core.fields.EncryptedCharField(
                help_text="Router password", max_length=255
            ),
        ),
        migrations.RunPython(encrypt_passwords, reverse_code=migrations.RunPython.noop),
    ]
