# Generated by Django 4.2.7 on 2026-03-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_router_snmp_community'),
        ('network', '0003_encrypt_router_passwords'),
    ]

    operations = [
    ]
