# Generated by Django 4.2.7 on 2026-03-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_merge_20260306_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='active_subscriptions_count',
            field=models.IntegerField(default=0, help_text='Cached count of active subscriptions'),
        ),
        migrations.AddField(
            model_name='router',
            name='total_bandwidth_usage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cached total bandwidth usage (GB)', max_digits=15),
        ),
    ]
