# Generated by Django 4.2.7 on 2025-09-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bytes_in', models.BigIntegerField(default=0, help_text='Total bytes received')),
                ('total_bytes_out', models.BigIntegerField(default=0, help_text='Total bytes sent')),
                ('active_connections', models.IntegerField(default=0, help_text='Active connections')),
                ('pppoe_users_count', models.IntegerField(default=0, help_text='Total PPPoE users')),
                ('pppoe_active_sessions', models.IntegerField(default=0, help_text='Active PPPoE sessions')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(help_text='Router for this snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='usage_snapshots', to='network.router')),
            ],
            options={
                'verbose_name': 'Usage Snapshot',
                'verbose_name_plural': 'Usage Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['router'], name='monitoring__router__e8be76_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_86eb82_idx')],
            },
        ),
        migrations.CreateModel(
            name='SNMPSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, help_text='CPU usage percentage', null=True)),
                ('memory_usage', models.FloatField(blank=True, help_text='Memory usage percentage', null=True)),
                ('disk_usage', models.FloatField(blank=True, help_text='Disk usage percentage', null=True)),
                ('interface_data', models.JSONField(default=dict, help_text='Interface bandwidth data')),
                ('uptime', models.BigIntegerField(blank=True, help_text='System uptime in seconds', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='System temperature in Celsius', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('router', models.ForeignKey(help_text='Router for this snapshot', on_delete=django.db.models.deletion.CASCADE, related_name='snmp_snapshots', to='network.router')),
            ],
            options={
                'verbose_name': 'SNMP Snapshot',
                'verbose_name_plural': 'SNMP Snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['router'], name='monitoring__router__713c55_idx'), models.Index(fields=['timestamp'], name='monitoring__timesta_040138_idx')],
            },
        ),
    ]
