# Generated by Django 4.2.7 on 2025-09-09 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_router_updates'),
        ('monitoring', '0002_router_metrics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='snmpsnapshot',
            name='monitoring__router__713c55_idx',
        ),
        migrations.RemoveIndex(
            model_name='snmpsnapshot',
            name='monitoring__timesta_040138_idx',
        ),
        migrations.RemoveIndex(
            model_name='usagesnapshot',
            name='monitoring__router__e8be76_idx',
        ),
        migrations.RemoveIndex(
            model_name='usagesnapshot',
            name='monitoring__timesta_86eb82_idx',
        ),
        migrations.RenameIndex(
            model_name='routermetric',
            new_name='monitoring__router__cd5380_idx',
            old_name='monitoring_routermetric_router_timestamp_idx',
        ),
        migrations.RemoveField(
            model_name='snmpsnapshot',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='snmpsnapshot',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='routermetric',
            name='router',
            field=models.ForeignKey(help_text='Router for this metric', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='network.router'),
        ),
        migrations.AlterField(
            model_name='snmpsnapshot',
            name='cpu_usage',
            field=models.FloatField(default=0.0, help_text='CPU usage percentage'),
        ),
        migrations.AlterField(
            model_name='snmpsnapshot',
            name='interface_data',
            field=models.JSONField(default=dict, help_text='Interface statistics'),
        ),
        migrations.AlterField(
            model_name='snmpsnapshot',
            name='memory_usage',
            field=models.FloatField(default=0.0, help_text='Memory usage percentage'),
        ),
        migrations.AlterField(
            model_name='snmpsnapshot',
            name='uptime',
            field=models.BigIntegerField(default=0, help_text='System uptime in seconds'),
        ),
        migrations.AlterField(
            model_name='usagesnapshot',
            name='active_connections',
            field=models.IntegerField(default=0, help_text='Active connections count'),
        ),
        migrations.AddIndex(
            model_name='snmpsnapshot',
            index=models.Index(fields=['router', '-timestamp'], name='monitoring__router__cabdbd_idx'),
        ),
        migrations.AddIndex(
            model_name='usagesnapshot',
            index=models.Index(fields=['router', '-timestamp'], name='monitoring__router__f2a3c2_idx'),
        ),
    ]
