# Generated by Django 4.2.7 on 2025-09-07 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ISP Admin Panel', help_text='Company name displayed in the system', max_length=255)),
                ('contact_email', models.EmailField(default='admin@ispadmin.com', help_text='Primary contact email address', max_length=254)),
                ('support_phone', models.CharField(default='+1 (555) 123-4567', help_text='Support phone number', max_length=50)),
                ('timezone', models.CharField(default='UTC', help_text='System timezone', max_length=50)),
                ('date_format', models.CharField(default='MM/DD/YYYY', help_text='Date format for display', max_length=20)),
                ('currency', models.CharField(default='USD', help_text='Default currency code', max_length=3)),
                ('language', models.CharField(default='en', help_text='System language code', max_length=10)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode')),
                ('auto_backup', models.BooleanField(default=True, help_text='Enable automatic backups')),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='Backup frequency', max_length=20)),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications')),
                ('sms_notifications', models.BooleanField(default=False, help_text='Enable SMS notifications')),
                ('api_rate_limit', models.PositiveIntegerField(default=1000, help_text='API rate limit per hour', validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000)])),
                ('session_timeout', models.PositiveIntegerField(default=30, help_text='Session timeout in minutes', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(480)])),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='Maximum login attempts before lockout', validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)])),
                ('password_min_length', models.PositiveIntegerField(default=8, help_text='Minimum password length', validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(20)])),
                ('password_require_uppercase', models.BooleanField(default=True, help_text='Require uppercase letters in passwords')),
                ('password_require_lowercase', models.BooleanField(default=True, help_text='Require lowercase letters in passwords')),
                ('password_require_numbers', models.BooleanField(default=True, help_text='Require numbers in passwords')),
                ('password_require_special_chars', models.BooleanField(default=True, help_text='Require special characters in passwords')),
                ('log_level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', help_text='System log level', max_length=20)),
                ('database_pool_size', models.PositiveIntegerField(default=10, help_text='Database connection pool size', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)])),
                ('cache_ttl', models.PositiveIntegerField(default=3600, help_text='Cache TTL in seconds', validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(86400)])),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
